default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  host: localhost
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: notes_agro_development

test:
  <<: *default
  database: notes_agro_test
production:
  <<: *default
  database: notes_agro_production
  username: notes_agro
  password: <%= ENV["NOTES_AGRO_DATABASE_PASSWORD"] %>
